### ISSUE TITLE
name 'Blender' is not defined

### ISSUE THREAD

**Issue by spooky** [Oygron/SupCom_Import_Export_Blender#4]
I get an error when trying to export a model:

name 'Blender' is not defined. - supcom-exporter.py line 853

This happens when the vertex group is empty (group exists, but no vertices are assigned)

**Comment by Oygron** [comment]
Hi, thanks for the issue, and sorry for the delay. 
The error message is now correct and does not result in a crash.

It happens in fact when a vertex is not assigned to a group.
