### ISSUE TITLE
UV problems

### ISSUE THREAD

**Issue by spooky** [Oygron/SupCom_Import_Export_Blender#5]
Another export error:
supcom-exporter.py: 875
TypeErrpr: 'NoneType' object is not subscriptable.
No idea what I should do with the UV to be able to export the model

**Comment by Oygron** [comment]
Hi, 

Thanks for the issue. It took me a while to figure it out. In fact, Supcom seems to support only triangulate faces, and the method to extract the UV is then for tris only (I did not code this one, only transcribed it to python3). 

The error is now explicit and does not result in a crash.
